export const CREATE_ROLE = "CREATE.ROLE";
export const EDIT_ROLE = "EDIT.ROLE";
export const VIEW_ROLE = "VIEW.ROLE";

export const CREATE_USER = "CREATE.USER";
export const EDIT_USER = "EDIT.USER";
export const VIEW_USER = "VIEW.USER";

export const VIEW_ORGANIZATION_DATA = "VIEW.ORGANIZATION.DATA";
export const EDIT_ORGANIZATION_DATA = "EDIT.ORGANIZATION.DATA";

export const VIEW_PASSENGER_STATUS = "VIEW.PASSENGER.STATUS";
export const EDIT_PASSENGER_STATUS = "EDIT.PASSENGER.STATUS";

export const VIEW_PASSENGER_DOCUMENT_TYPE = "VIEW.PASSENGER.DOCUMENT.TYPE";
export const CREATE_PASSENGER_DOCUMENT_TYPE = "CREATE.PASSENGER.DOCUMENT.TYPE";
export const EDIT_PASSENGER_DOCUMENT_TYPE = "EDIT.PASSENGER.DOCUMENT.TYPE";

export const VIEW_JOB_CATALOG = "VIEW.JOB.CATALOG";
export const CREATE_JOB_CATALOG = "CREATE.JOB.CATALOG";
export const EDIT_JOB_CATALOG = "EDIT.JOB.CATALOG";

export const CREATE_COUNTRY = "CREATE.COUNTRY";
export const EDIT_COUNTRY = "EDIT.COUNTRY";
export const VIEW_COUNTRY = "VIEW.COUNTRY";

export const CREATE_QUALIFICATION = "CREATE.QUALIFICATION";
export const EDIT_QUALIFICATION = "EDIT.QUALIFICATION";
export const VIEW_QUALIFICATION = "VIEW.QUALIFICATION";
